FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# Install software-properties-common to use add-apt-repository
RUN apt update && apt install -y software-properties-common \
    && add-apt-repository ppa:neovim-ppa/stable -y \
    && apt update && apt install -y \
    wget \
    git \
    build-essential \
    libffi-dev \
    libtiff-dev \
    python3 \
    python3-pip \
    python-is-python3 \
    jq \
    curl \
    locales \
    locales-all \
    tzdata \
    neovim \
    nano \
    && rm -rf /var/lib/apt/lists/*

# Download and install conda
RUN wget "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-$(arch).sh" -O miniconda.sh \
    && bash miniconda.sh -b -p /opt/miniconda3

# Add conda to PATH
ENV PATH=/opt/miniconda3/bin:$PATH

# Add conda to shell startup scripts like .bashrc (DO NOT REMOVE THIS)
RUN conda init --all
RUN conda config --append channels conda-forge
RUN git config --global --add safe.directory /Mercor_Interview
RUN adduser --disabled-password --gecos 'interviewer' nonroot
RUN conda create -n testbed

WORKDIR /Mercor_Interview
